-- Viel Glück fleet manager — initial Postgres schema (ported from SQLite).
-- Run once in the Supabase SQL editor (or `supabase db push`).
-- CamelCase columns are quoted to preserve case: the API returns rows as-is
-- and the frontend expects camelCase JSON keys.

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text UNIQUE NOT NULL,
  password text NOT NULL,
  name text NOT NULL,
  role text NOT NULL DEFAULT 'Operations'
);

CREATE TABLE vehicles (
  id text PRIMARY KEY,
  reg text UNIQUE NOT NULL,
  vin text,
  make text,
  model text,
  year integer,
  type text,
  color text,
  mileage integer DEFAULT 0,
  "motIssue" text,
  "motExpiry" text,
  "insuranceExpiry" text,
  status text DEFAULT 'Available',
  location text DEFAULT 'Main Office',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE customers (
  id text PRIMARY KEY,
  name text NOT NULL,
  phone text,
  email text,
  "idNumber" text,
  license text,
  emergency text,
  "nextOfKinName" text,
  "nextOfKinContact" text,
  "physicalAddress" text,
  "workPlace" text,
  "workContact" text,
  notes text,
  balance double precision DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE bookings (
  id text PRIMARY KEY,
  "customerId" text NOT NULL REFERENCES customers(id),
  "customerName" text,
  "vehicleId" text NOT NULL REFERENCES vehicles(id),
  "vehicleReg" text,
  pickup text,
  "pickupTime" text,
  "returnDate" text,
  status text DEFAULT 'Pending',
  rate double precision,
  total double precision,
  deposit double precision,
  paid double precision DEFAULT 0,
  "tripType" text DEFAULT 'Local',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE payments (
  id text PRIMARY KEY,
  "bookingId" text,
  "customerId" text,
  "customerName" text,
  amount double precision,
  type text,
  method text DEFAULT 'Cash',
  date text,
  status text DEFAULT 'Completed',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE maintenance (
  id text PRIMARY KEY,
  "vehicleId" text NOT NULL REFERENCES vehicles(id),
  "vehicleReg" text,
  type text,
  date text,
  cost double precision DEFAULT 0,
  status text DEFAULT 'Scheduled',
  notes text,
  "nextDue" text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE inspections (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicleId" text NOT NULL,
  "bookingId" text,
  type text DEFAULT 'pre',
  areas text,
  notes text,
  created_at timestamptz DEFAULT now()
);

-- The app talks to Postgres directly with its own JWT auth layer; RLS with no
-- policies blocks Supabase's auto-generated REST API from exposing these tables.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance ENABLE ROW LEVEL SECURITY;
ALTER TABLE inspections ENABLE ROW LEVEL SECURITY;
